# Part 1

In [276]:
with open('input1.txt') as f:
    lines = f.read().splitlines()

In [277]:
import numpy as np

current = -1

bingo = [0]*lines.count('')
random = lines[0].split(',')

for i in range(lines.count('')):
    bingo[i] = np.zeros((5,5))
    for j in range(5):
        for k in range(5):
            bingo[i][j, k] = int(lines[6*i+2+j].split()[k])
        

In [278]:
def replace(bingo, num):
    bingo[np.where(bingo == num)[0], np.where(bingo == num)[1]] = -1
    return bingo

In [279]:
def checker(bingo):
    for i in range(len(bingo[0])):
        if (sum(bingo[i,:]) == -5 or sum(bingo[:,i]) == -5) and bingo[0,0] != float('inf'):
            return(1)
    return(0)

In [280]:
def bingotime(bingo, random):
    count = 0
    for x in random:
        for i in range(len(bingo)):
            bingo[i] = replace(bingo[i], int(x))
            if checker(bingo[i]):
                count += 1
                if count == len(bingo):
                    bingo[i][np.where(bingo[i] == -1)[0], np.where(bingo[i] == -1)[1]] = 0
                    return(int(x)*sum(sum(bingo[i])))
                bingo[i][0,0] = float('inf')

In [281]:
print(bingotime(bingo, random))

18063.0


In [203]:
bingo

[array([[22., -1., -1., -1., -1.],
        [ 8., -1., -1., -1., -1.],
        [-1., -1., -1., -1., -1.],
        [ 6., -1.,  3., 18., -1.],
        [ 1., 12., 20., 15., 19.]]),
 array([[ 3., 15.,  0.,  0., 22.],
        [ 0., 18.,  0.,  0.,  0.],
        [19.,  8.,  0., 25.,  0.],
        [20.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0., 12.,  6.]]),
 array([[-1., -1., -1., -1., -1.],
        [-1., -1., 15., -1., 19.],
        [18.,  8., -1., 26., 20.],
        [22., -1., 13.,  6., -1.],
        [-1., -1., 12.,  3., -1.]])]

In [134]:
bingo[0][0,0] = -1

In [135]:
bingo[0]

array([[-1., 13.,  0.,  0.,  0.],
       [ 8.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0., 16.,  0.],
       [ 6., 10.,  3., 18.,  0.],
       [ 1., 12., 20., 15., 19.]])

In [137]:
sum(sum(bingo[0]))

140.0

In [148]:
bingo[0][np.where(bingo[0] == -1)[0], np.where(bingo[0] == -1)[1]] = 0

In [149]:
bingo[0]

array([[ 0., 13.,  0.,  0.,  0.],
       [ 8.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0., 16.,  0.],
       [ 6., 10.,  3., 18.,  0.],
       [ 1., 12., 20., 15., 19.]])

In [147]:
bingo[0][0, 0] = -1
bingo[0][1,1] = -1
bingo[0]

array([[-1., 13.,  0.,  0.,  0.],
       [ 8., -1.,  0.,  0.,  0.],
       [ 0.,  0.,  0., 16.,  0.],
       [ 6., 10.,  3., 18.,  0.],
       [ 1., 12., 20., 15., 19.]])