In [450]:
with open('input1.txt') as f:
    lines = f.read().splitlines()

In [451]:
import numpy as np

grid = np.zeros((len(lines), len(lines[0])))
for i in range(len(lines)):
    grid[i,:] = np.array(list(map(int, list(lines[i]))))

In [452]:
def step(grid):
    grid += 1
    
    todox, todoy = np.where(grid == 10)
    i = 0
    
    while i < len(todox):
        lowerj = -1
        upperj = 2
        if todox[i] == 0:
            lowerj = 0
        elif todox[i] == len(grid[0])-1:
            upperj = 1
            
        lowerk = -1
        upperk = 2
        if todoy[i] == 0:
            lowerk = 0
        elif todoy[i] == len(grid)-1:
            upperk = 1
            
        for j in range(lowerj, upperj):
            for k in range(lowerk, upperk):
                if j != 0 or k != 0:
                    grid[todox[i]+j, todoy[i]+k] += 1

                    if grid[todox[i]+j, todoy[i]+k] == 10:
                        todox = np.append(todox, todox[i]+j)
                        todoy = np.append(todoy, todoy[i]+k)
        i += 1
    
    grid[np.where(grid > 9)] = 0
    
    return(grid, len(todox))

In [453]:
tot = 0
i=0
while i > -1:
    grid, num = step(grid)
    tot += num

    if num == len(grid)*len(grid[0]):
        print(i+1)
        print(grid)
        grid.append()
    i+=1
grid

337
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [412]:
tot

1655

In [295]:
grid

array([[0., 0., 0., 0., 9.],
       [0., 0., 9., 9., 0.],
       [0., 9., 6., 7., 0.],
       [0., 9., 7., 7., 9.],
       [9., 0., 0., 9., 8.]])

In [66]:
np.where(a[0]==4)[0] in np.where(a[1] == 5)[0]

False

In [46]:
np.where(a[0]==2)[0]

array([3, 4])

In [71]:
a = np.where(a[1] == 2)[0]

IndexError: list index out of range

In [44]:
a

(array([1, 1, 1, 2, 2, 3, 3, 3]), array([1, 2, 3, 1, 3, 1, 2, 3]))

In [52]:
for b in [x,y]:
    print(b)

[1 1 1 2 2 3 3 3]
[1 2 3 1 3 1 2 3]


In [74]:
np.append(a[0], 1)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1])